In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
data=pd.read_csv("C:\\Users\\raghu\\Downloads\\nba_final.csv")

In [4]:
data

,Rk,Player.x,Player_ID,Pos1,Pos2,Age,Tm,G,GS,MP,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,A.J. Hammons,hammoaj01,C,NaN,24,DAL,22,0,7.4,...,West,Front,786,123,NaN,NaN,NaN,NaN,83.5,No
1,58,Aaron Brooks,brookaa01,PG,NaN,32,IND,65,0,13.8,...,Est,Back,2474,64,NaN,NaN,NaN,NaN,48.2,No
2,157,Aaron Gordon,gordoaa01,SF,NaN,21,ORL,80,72,28.7,...,Est,Front,22774,29,NaN,NaN,NaN,NaN,40.0,No
3,352,Adreian Payne,paynead01,PF,NaN,25,MIN,18,0,7.5,...,West,Front,861,120,1.0,52.0,NaN,NaN,75.5,No
4,10,Al-Farouq Aminu,aminual01,PF,NaN,26,POR,61,25,29.1,...,West,Front,4971,69,7.0,23.0,NaN,NaN,42.8,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,109,Zach Collins,colliza01,C,NaN,21,POR,77,0,17.6,...,West,Front,16287,74,1.0,52.0,0.0,8.0,86.8,No
1404,294,Zach LaVine,lavinza01,SG,NaN,23,CHI,63,62,34.5,...,Est,Back,519746,7,17.0,8.0,0.0,8.0,36.5,No
1405,308,Zach Lofton,loftoza01,SG,NaN,26,DET,1,0,4.0,...,Est,Back,136,114,0.0,61.0,0.0,8.0,132.2,No
1406,393,Zaza Pachulia,pachuza01,C,NaN,34,DET,68,3,12.9,...,Est,Front,21525,50,2.0,41.0,0.0,7.0,69.8,No
1407,457,Zhaire Smith,smithzh01,SG,NaN,19,PHI,6,2,18.5,...,Est,Back,3985,91,0.0,61.0,0.0,8.0,120.8,No

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1408 entries, 0 to 1407
Data columns (total 45 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rk          1408 non-null   int64
 1   Player.x    1408 non-null   object
 2   Player_ID   1408 non-null   object
 3   Pos1        1408 non-null   object
 4   Pos2        12 non-null     object
 5   Age         1408 non-null   int64
 6   Tm          1408 non-null   object
 7   G           1408 non-null   int64
 8   GS          1408 non-null   int64
 9   MP          1408 non-null   float64
 10  FG          1408 non-null   float64
 11  FGA         1408 non-null   float64
 12  FG.         1404 non-null   float64
 13  X3P         1408 non-null   float64
 14  X3PA        1408 non-null   float64
 15  X3P.        1309 non-null   float64
 16  X2P         1408 non-null   float64
 17  X2PA        1408 non-null   float64
 18  X2P.        1393 non-null   float64
 19  eFG.        1404 non-null   float64
 20  FT          1408 non-null   float64
 21  FTA         1408 non-null   float64
 22  FT.         1361 non-null   float64
 23  ORB         1408 non-null   float64
 24  DRB         1408 non-null   float64
 25  TRB         1408 non-null   float64
 26  AST         1408 non-null   float64
 27  STL         1408 non-null   float64
 28  BLK         1408 non-null   float64
 29  TOV         1408 non-null   float64
 30  PF          1408 non-null   float64
 31  PTS         1408 non-null   float64
 32  Salary      1346 non-null   float64
 33  mean_views  1270 non-null   float64
 34  Season      1408 non-null   object
 35  Conference  1408 non-null   object
 36  Role        1408 non-null   object
 37  Fvot        1408 non-null   int64
 38  FRank       1408 non-null   int64
 39  Pvot        1249 non-null   float64
 40  PRank       1249 non-null   float64
 41  Mvot        1004 non-null   float64
 42  MRank       1004 non-null   float64
 43  Score       1408 non-null   float64
 44  Play        1408 non-null   object
dtypes: float64(30), int64(6), object(9)
memory usage: 495.1+ KB

In [6]:
data.isnull().sum()

Rk               0
Player.x         0
Player_ID        0
Pos1             0
Pos2          1396
Age              0
Tm               0
G                0
GS               0
MP               0
FG               0
FGA              0
FG.              4
X3P              0
X3PA             0
X3P.            99
X2P              0
X2PA             0
X2P.            15
eFG.             4
FT               0
FTA              0
FT.             47
ORB              0
DRB              0
TRB              0
AST              0
STL              0
BLK              0
TOV              0
PF               0
PTS              0
Salary          62
mean_views     138
Season           0
Conference       0
Role             0
Fvot             0
FRank            0
Pvot           159
PRank          159
Mvot           404
MRank          404
Score            0
Play             0
dtype: int64

In [8]:
data["Pos2"].replace(np.nan,"None",inplace=True)

In [9]:
data.fillna(0,inplace=True)

In [10]:
data.drop(columns=['Player.x','Player_ID'],inplace=True)

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le=LabelEncoder()

In [13]:
for column in data.select_dtypes("object"):
    data[column]=le.fit_transform(data[column])

In [14]:
X=data.drop("Play",axis=1)
y=data["Play"]

In [16]:
from sklearn.preprocessing import StandardScaler #scaling is required when you are dealing with LDA

In [17]:
scaler=StandardScaler()

In [18]:
X=scaler.fit_transform(X)
X

array([[-0.58191469, -1.40108842, -0.07184075, ..., -0.16623906,
        -1.46817686,  0.19138945],
       [-1.32505241, -0.01428174, -0.07184075, ..., -0.16623906,
        -1.46817686, -0.66146791],
       [-0.66817174,  0.67912159, -0.07184075, ..., -0.16623906,
        -1.46817686, -0.85958209],
       ...,
       [ 0.33373715,  1.37252493, -0.07184075, ..., -0.16623906,
         0.83574403,  1.36799438],
       [ 0.8977256 , -1.40108842, -0.07184075, ..., -0.16623906,
         0.54775392, -0.13960618],
       [ 1.32237572,  1.37252493, -0.07184075, ..., -0.16623906,
         0.83574403,  1.09256735]])

In [19]:
d=data.drop('Play',axis=1)
col=list(d.columns)

In [20]:
X=pd.DataFrame(X,columns=col)

In [21]:
X

,Rk,Pos1,Pos2,Age,Tm,G,GS,MP,FG,FGA,...,Season,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score
0,-0.581915,-1.401088,-0.071841,-0.499694,-0.978040,-1.335031,-0.904118,-1.408249,-1.129079,-1.148786,...,-1.278177,1.0,0.898580,-0.272852,1.674613,-0.288505,-1.476607,-0.166239,-1.468177,0.191389
1,-1.325052,-0.014282,-0.071841,1.369015,-0.397581,0.453360,-0.904118,-0.702068,-0.624704,-0.560576,...,-1.278177,-1.0,-1.112867,-0.268913,0.065584,-0.288505,-1.476607,-0.166239,-1.468177,-0.661468
2,-0.668172,0.679122,-0.071841,-1.200460,0.763336,1.077217,1.608585,0.942012,0.750863,0.790129,...,-1.278177,-1.0,0.898580,-0.221535,-0.888925,-0.288505,-1.476607,-0.166239,-1.468177,-0.859582
3,0.625684,-0.707685,-0.071841,-0.266105,0.298969,-1.501393,-0.904118,-1.397215,-0.899817,-0.909145,...,-1.278177,1.0,0.898580,-0.272677,1.592798,-0.248527,0.523712,-0.166239,-1.468177,-0.001893
4,-1.643540,-0.707685,-0.071841,-0.032517,1.111611,0.286998,-0.031652,0.986148,-0.120330,0.092991,...,-1.278177,1.0,0.898580,-0.263085,0.201942,-0.008660,-0.591851,-0.166239,-1.468177,-0.791933
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,-0.986659,-1.401088,-0.071841,-1.200460,1.111611,0.952446,-0.904118,-0.282772,-0.349591,-0.429863,...,1.210998,1.0,0.898580,-0.236675,0.338301,-0.248527,0.523712,-0.166239,0.835744,0.271118
1404,0.240845,1.372525,-0.071841,-0.733283,-1.326315,0.370179,1.259599,1.581989,2.355691,2.358690,...,1.210998,-1.0,-1.112867,0.938327,-1.488902,0.391118,-1.168866,-0.166239,0.835744,-0.944143
1405,0.333737,1.372525,-0.071841,-0.032517,-0.745856,-2.208431,-0.904118,-1.783409,-1.495896,-1.344856,...,1.210998,-1.0,-1.112867,-0.274369,1.429168,-0.288505,0.869922,-0.166239,0.835744,1.367994
1406,0.897726,-1.401088,-0.071841,1.836193,-0.745856,0.578131,-0.799422,-0.801374,-0.899817,-0.952716,...,1.210998,-1.0,0.898580,-0.224450,-0.316220,-0.208549,0.100568,-0.166239,0.547754,-0.139606
1407,1.322376,1.372525,-0.071841,-1.667637,0.879428,-2.000478,-0.834321,-0.183465,-0.441295,-0.320935,...,1.210998,-1.0,-1.112867,-0.265386,0.801919,-0.288505,0.869922,-0.166239,0.835744,1.092567

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [25]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [26]:
y_pred=model.predict(x_test)

In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9822695035460993

# LDA

In [29]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [30]:
X

,Rk,Pos1,Pos2,Age,Tm,G,GS,MP,FG,FGA,...,Season,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score
0,-0.581915,-1.401088,-0.071841,-0.499694,-0.978040,-1.335031,-0.904118,-1.408249,-1.129079,-1.148786,...,-1.278177,1.0,0.898580,-0.272852,1.674613,-0.288505,-1.476607,-0.166239,-1.468177,0.191389
1,-1.325052,-0.014282,-0.071841,1.369015,-0.397581,0.453360,-0.904118,-0.702068,-0.624704,-0.560576,...,-1.278177,-1.0,-1.112867,-0.268913,0.065584,-0.288505,-1.476607,-0.166239,-1.468177,-0.661468
2,-0.668172,0.679122,-0.071841,-1.200460,0.763336,1.077217,1.608585,0.942012,0.750863,0.790129,...,-1.278177,-1.0,0.898580,-0.221535,-0.888925,-0.288505,-1.476607,-0.166239,-1.468177,-0.859582
3,0.625684,-0.707685,-0.071841,-0.266105,0.298969,-1.501393,-0.904118,-1.397215,-0.899817,-0.909145,...,-1.278177,1.0,0.898580,-0.272677,1.592798,-0.248527,0.523712,-0.166239,-1.468177,-0.001893
4,-1.643540,-0.707685,-0.071841,-0.032517,1.111611,0.286998,-0.031652,0.986148,-0.120330,0.092991,...,-1.278177,1.0,0.898580,-0.263085,0.201942,-0.008660,-0.591851,-0.166239,-1.468177,-0.791933
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,-0.986659,-1.401088,-0.071841,-1.200460,1.111611,0.952446,-0.904118,-0.282772,-0.349591,-0.429863,...,1.210998,1.0,0.898580,-0.236675,0.338301,-0.248527,0.523712,-0.166239,0.835744,0.271118
1404,0.240845,1.372525,-0.071841,-0.733283,-1.326315,0.370179,1.259599,1.581989,2.355691,2.358690,...,1.210998,-1.0,-1.112867,0.938327,-1.488902,0.391118,-1.168866,-0.166239,0.835744,-0.944143
1405,0.333737,1.372525,-0.071841,-0.032517,-0.745856,-2.208431,-0.904118,-1.783409,-1.495896,-1.344856,...,1.210998,-1.0,-1.112867,-0.274369,1.429168,-0.288505,0.869922,-0.166239,0.835744,1.367994
1406,0.897726,-1.401088,-0.071841,1.836193,-0.745856,0.578131,-0.799422,-0.801374,-0.899817,-0.952716,...,1.210998,-1.0,0.898580,-0.224450,-0.316220,-0.208549,0.100568,-0.166239,0.547754,-0.139606
1407,1.322376,1.372525,-0.071841,-1.667637,0.879428,-2.000478,-0.834321,-0.183465,-0.441295,-0.320935,...,1.210998,-1.0,-1.112867,-0.265386,0.801919,-0.288505,0.869922,-0.166239,0.835744,1.092567

In [35]:
lda = LinearDiscriminantAnalysis()

In [36]:
X=lda.fit_transform(X,y)

In [37]:
X

array([[-1.03229414],
       [-0.50134906],
       [-0.57346384],
       ...,
       [-0.72836767],
       [-0.37294989],
       [-0.8653202 ]])

In [39]:
X.shape

(1408, 1)

In [38]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1403    0
1404    0
1405    0
1406    0
1407    0
Name: Play, Length: 1408, dtype: int32

In [ ]:
# no of columns that are created ->min(n_classes-1,no_features) classes->output column

In [40]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [41]:
model1=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [42]:
y_pred=model.predict(x_test)

In [43]:
accuracy_score(y_test,y_pred)

0.9858156028368794