In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt
import seaborn as sns

C:\Users\raghu\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.25.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
from sklearn.linear_model import LogisticRegression

In [4]:
from sklearn.metrics import accuracy_score

In [5]:
data=pd.read_csv("C:\\Users\\raghu\\Downloads\\nba_final.csv")

In [6]:
data

,Rk,Player.x,Player_ID,Pos1,Pos2,Age,Tm,G,GS,MP,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,A.J. Hammons,hammoaj01,C,NaN,24,DAL,22,0,7.4,...,West,Front,786,123,NaN,NaN,NaN,NaN,83.5,No
1,58,Aaron Brooks,brookaa01,PG,NaN,32,IND,65,0,13.8,...,Est,Back,2474,64,NaN,NaN,NaN,NaN,48.2,No
2,157,Aaron Gordon,gordoaa01,SF,NaN,21,ORL,80,72,28.7,...,Est,Front,22774,29,NaN,NaN,NaN,NaN,40.0,No
3,352,Adreian Payne,paynead01,PF,NaN,25,MIN,18,0,7.5,...,West,Front,861,120,1.0,52.0,NaN,NaN,75.5,No
4,10,Al-Farouq Aminu,aminual01,PF,NaN,26,POR,61,25,29.1,...,West,Front,4971,69,7.0,23.0,NaN,NaN,42.8,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,109,Zach Collins,colliza01,C,NaN,21,POR,77,0,17.6,...,West,Front,16287,74,1.0,52.0,0.0,8.0,86.8,No
1404,294,Zach LaVine,lavinza01,SG,NaN,23,CHI,63,62,34.5,...,Est,Back,519746,7,17.0,8.0,0.0,8.0,36.5,No
1405,308,Zach Lofton,loftoza01,SG,NaN,26,DET,1,0,4.0,...,Est,Back,136,114,0.0,61.0,0.0,8.0,132.2,No
1406,393,Zaza Pachulia,pachuza01,C,NaN,34,DET,68,3,12.9,...,Est,Front,21525,50,2.0,41.0,0.0,7.0,69.8,No
1407,457,Zhaire Smith,smithzh01,SG,NaN,19,PHI,6,2,18.5,...,Est,Back,3985,91,0.0,61.0,0.0,8.0,120.8,No

In [7]:
data.dtypes

Rk              int64
Player.x       object
Player_ID      object
Pos1           object
Pos2           object
Age             int64
Tm             object
G               int64
GS              int64
MP            float64
FG            float64
FGA           float64
FG.           float64
X3P           float64
X3PA          float64
X3P.          float64
X2P           float64
X2PA          float64
X2P.          float64
eFG.          float64
FT            float64
FTA           float64
FT.           float64
ORB           float64
DRB           float64
TRB           float64
AST           float64
STL           float64
BLK           float64
TOV           float64
PF            float64
PTS           float64
Salary        float64
mean_views    float64
Season         object
Conference     object
Role           object
Fvot            int64
FRank           int64
Pvot          float64
PRank         float64
Mvot          float64
MRank         float64
Score         float64
Play           object
dtype: object

In [8]:
data.shape

(1408, 45)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1408 entries, 0 to 1407
Data columns (total 45 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rk          1408 non-null   int64
 1   Player.x    1408 non-null   object
 2   Player_ID   1408 non-null   object
 3   Pos1        1408 non-null   object
 4   Pos2        12 non-null     object
 5   Age         1408 non-null   int64
 6   Tm          1408 non-null   object
 7   G           1408 non-null   int64
 8   GS          1408 non-null   int64
 9   MP          1408 non-null   float64
 10  FG          1408 non-null   float64
 11  FGA         1408 non-null   float64
 12  FG.         1404 non-null   float64
 13  X3P         1408 non-null   float64
 14  X3PA        1408 non-null   float64
 15  X3P.        1309 non-null   float64
 16  X2P         1408 non-null   float64
 17  X2PA        1408 non-null   float64
 18  X2P.        1393 non-null   float64
 19  eFG.        1404 non-null   float64
 20  FT          1408 non-null   float64
 21  FTA         1408 non-null   float64
 22  FT.         1361 non-null   float64
 23  ORB         1408 non-null   float64
 24  DRB         1408 non-null   float64
 25  TRB         1408 non-null   float64
 26  AST         1408 non-null   float64
 27  STL         1408 non-null   float64
 28  BLK         1408 non-null   float64
 29  TOV         1408 non-null   float64
 30  PF          1408 non-null   float64
 31  PTS         1408 non-null   float64
 32  Salary      1346 non-null   float64
 33  mean_views  1270 non-null   float64
 34  Season      1408 non-null   object
 35  Conference  1408 non-null   object
 36  Role        1408 non-null   object
 37  Fvot        1408 non-null   int64
 38  FRank       1408 non-null   int64
 39  Pvot        1249 non-null   float64
 40  PRank       1249 non-null   float64
 41  Mvot        1004 non-null   float64
 42  MRank       1004 non-null   float64
 43  Score       1408 non-null   float64
 44  Play        1408 non-null   object
dtypes: float64(30), int64(6), object(9)
memory usage: 495.1+ KB

In [10]:
data.isnull().sum()

Rk               0
Player.x         0
Player_ID        0
Pos1             0
Pos2          1396
Age              0
Tm               0
G                0
GS               0
MP               0
FG               0
FGA              0
FG.              4
X3P              0
X3PA             0
X3P.            99
X2P              0
X2PA             0
X2P.            15
eFG.             4
FT               0
FTA              0
FT.             47
ORB              0
DRB              0
TRB              0
AST              0
STL              0
BLK              0
TOV              0
PF               0
PTS              0
Salary          62
mean_views     138
Season           0
Conference       0
Role             0
Fvot             0
FRank            0
Pvot           159
PRank          159
Mvot           404
MRank          404
Score            0
Play             0
dtype: int64

In [11]:
#total null values
data.isnull().sum().sum()

2891

In [12]:
#pos2 has too many missinng values
data["Pos2"].fillna("None",inplace=True)

In [13]:
data.fillna(0,inplace=True)

In [14]:
data.drop(columns=['Player.x','Player_ID'],inplace=True)

In [15]:
data.select_dtypes('object')

     Pos1  Pos2   Tm   Season Conference   Role Play
0       C  None  DAL  2016-17       West  Front   No
1      PG  None  IND  2016-17        Est   Back   No
2      SF  None  ORL  2016-17        Est  Front   No
3      PF  None  MIN  2016-17       West  Front   No
4      PF  None  POR  2016-17       West  Front   No
...   ...   ...  ...      ...        ...    ...  ...
1403    C  None  POR  2018-19       West  Front   No
1404   SG  None  CHI  2018-19        Est   Back   No
1405   SG  None  DET  2018-19        Est   Back   No
1406    C  None  DET  2018-19        Est  Front   No
1407   SG  None  PHI  2018-19        Est   Back   No

[1408 rows x 7 columns]

In [16]:
data.select_dtypes('number')

,Rk,Age,G,GS,MP,FG,FGA,FG.,X3P,X3PA,...,PTS,Salary,mean_views,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score
0,170,24,22,0,7.4,0.8,1.9,0.405,0.2,0.5,...,2.2,0.0,3.320000,786,123,0.0,0.0,0.0,0.0,83.5
1,58,32,65,0,13.8,1.9,4.6,0.403,0.7,2.0,...,5.0,2700000.0,11.155738,2474,64,0.0,0.0,0.0,0.0,48.2
2,157,21,80,72,28.7,4.9,10.8,0.454,1.0,3.3,...,12.7,4351320.0,1713.986339,22774,29,0.0,0.0,0.0,0.0,40.0
3,352,25,18,0,7.5,1.3,3.0,0.426,0.2,0.8,...,3.5,2022240.0,205.855191,861,120,1.0,52.0,0.0,0.0,75.5
4,10,26,61,25,29.1,3.0,7.6,0.393,1.1,3.5,...,8.7,7680965.0,604.341530,4971,69,7.0,23.0,0.0,0.0,42.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,109,21,77,0,17.6,2.5,5.2,0.473,0.5,1.6,...,6.6,3628920.0,470.320548,16287,74,1.0,52.0,0.0,8.0,86.8
1404,294,23,63,62,34.5,8.4,18.0,0.467,1.9,5.1,...,23.7,19500000.0,1415.268493,519746,7,17.0,8.0,0.0,8.0,36.5
1405,308,26,1,0,4.0,0.0,1.0,0.000,0.0,1.0,...,0.0,77250.0,0.000000,136,114,0.0,61.0,0.0,8.0,132.2
1406,393,34,68,3,12.9,1.3,2.8,0.440,0.0,0.1,...,3.9,2393887.0,1183.576503,21525,50,2.0,41.0,0.0,7.0,69.8
1407,457,19,6,2,18.5,2.3,5.7,0.412,1.0,2.7,...,6.7,2615160.0,469.912329,3985,91,0.0,61.0,0.0,8.0,120.8

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le=LabelEncoder()

In [19]:
for column in data.select_dtypes("object"):
    data[column]=le.fit_transform(data[column])

In [20]:
data

,Rk,Pos1,Pos2,Age,Tm,G,GS,MP,FG,FGA,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,0,1,24,6,22,0,7.4,0.8,1.9,...,1,1,786,123,0.0,0.0,0.0,0.0,83.5,0
1,58,2,1,32,11,65,0,13.8,1.9,4.6,...,0,0,2474,64,0.0,0.0,0.0,0.0,48.2,0
2,157,3,1,21,21,80,72,28.7,4.9,10.8,...,0,1,22774,29,0.0,0.0,0.0,0.0,40.0,0
3,352,1,1,25,17,18,0,7.5,1.3,3.0,...,1,1,861,120,1.0,52.0,0.0,0.0,75.5,0
4,10,1,1,26,24,61,25,29.1,3.0,7.6,...,1,1,4971,69,7.0,23.0,0.0,0.0,42.8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,109,0,1,21,24,77,0,17.6,2.5,5.2,...,1,1,16287,74,1.0,52.0,0.0,8.0,86.8,0
1404,294,4,1,23,3,63,62,34.5,8.4,18.0,...,0,0,519746,7,17.0,8.0,0.0,8.0,36.5,0
1405,308,4,1,26,8,1,0,4.0,0.0,1.0,...,0,0,136,114,0.0,61.0,0.0,8.0,132.2,0
1406,393,0,1,34,8,68,3,12.9,1.3,2.8,...,0,1,21525,50,2.0,41.0,0.0,7.0,69.8,0
1407,457,4,1,19,22,6,2,18.5,2.3,5.7,...,0,0,3985,91,0.0,61.0,0.0,8.0,120.8,0

# Machine Learning Process

In [21]:
X=data.drop("Play",axis=1)
y=data["Play"]

In [22]:
X

,Rk,Pos1,Pos2,Age,Tm,G,GS,MP,FG,FGA,...,Season,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score
0,170,0,1,24,6,22,0,7.4,0.8,1.9,...,0,1,1,786,123,0.0,0.0,0.0,0.0,83.5
1,58,2,1,32,11,65,0,13.8,1.9,4.6,...,0,0,0,2474,64,0.0,0.0,0.0,0.0,48.2
2,157,3,1,21,21,80,72,28.7,4.9,10.8,...,0,0,1,22774,29,0.0,0.0,0.0,0.0,40.0
3,352,1,1,25,17,18,0,7.5,1.3,3.0,...,0,1,1,861,120,1.0,52.0,0.0,0.0,75.5
4,10,1,1,26,24,61,25,29.1,3.0,7.6,...,0,1,1,4971,69,7.0,23.0,0.0,0.0,42.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,109,0,1,21,24,77,0,17.6,2.5,5.2,...,2,1,1,16287,74,1.0,52.0,0.0,8.0,86.8
1404,294,4,1,23,3,63,62,34.5,8.4,18.0,...,2,0,0,519746,7,17.0,8.0,0.0,8.0,36.5
1405,308,4,1,26,8,1,0,4.0,0.0,1.0,...,2,0,0,136,114,0.0,61.0,0.0,8.0,132.2
1406,393,0,1,34,8,68,3,12.9,1.3,2.8,...,2,0,1,21525,50,2.0,41.0,0.0,7.0,69.8
1407,457,4,1,19,22,6,2,18.5,2.3,5.7,...,2,0,0,3985,91,0.0,61.0,0.0,8.0,120.8

In [23]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1403    0
1404    0
1405    0
1406    0
1407    0
Name: Play, Length: 1408, dtype: int32

# scaling of the data is required when you are dealing with PCA or LDA

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
scaler=StandardScaler()

In [26]:
X=scaler.fit_transform(X)

In [27]:
X #after scaling it becomes 2d array

array([[-0.58191469, -1.40108842, -0.07184075, ..., -0.16623906,
        -1.46817686,  0.19138945],
       [-1.32505241, -0.01428174, -0.07184075, ..., -0.16623906,
        -1.46817686, -0.66146791],
       [-0.66817174,  0.67912159, -0.07184075, ..., -0.16623906,
        -1.46817686, -0.85958209],
       ...,
       [ 0.33373715,  1.37252493, -0.07184075, ..., -0.16623906,
         0.83574403,  1.36799438],
       [ 0.8977256 , -1.40108842, -0.07184075, ..., -0.16623906,
         0.54775392, -0.13960618],
       [ 1.32237572,  1.37252493, -0.07184075, ..., -0.16623906,
         0.83574403,  1.09256735]])

In [ ]:
d=data.drop('Play',axis=1)

In [34]:
X=pd.DataFrame(X,columns=col)

In [ ]:
col=list(d.columns)

In [35]:
X

,Rk,Pos1,Pos2,Age,Tm,G,GS,MP,FG,FGA,...,Season,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score
0,-0.581915,-1.401088,-0.071841,-0.499694,-0.978040,-1.335031,-0.904118,-1.408249,-1.129079,-1.148786,...,-1.278177,1.0,0.898580,-0.272852,1.674613,-0.288505,-1.476607,-0.166239,-1.468177,0.191389
1,-1.325052,-0.014282,-0.071841,1.369015,-0.397581,0.453360,-0.904118,-0.702068,-0.624704,-0.560576,...,-1.278177,-1.0,-1.112867,-0.268913,0.065584,-0.288505,-1.476607,-0.166239,-1.468177,-0.661468
2,-0.668172,0.679122,-0.071841,-1.200460,0.763336,1.077217,1.608585,0.942012,0.750863,0.790129,...,-1.278177,-1.0,0.898580,-0.221535,-0.888925,-0.288505,-1.476607,-0.166239,-1.468177,-0.859582
3,0.625684,-0.707685,-0.071841,-0.266105,0.298969,-1.501393,-0.904118,-1.397215,-0.899817,-0.909145,...,-1.278177,1.0,0.898580,-0.272677,1.592798,-0.248527,0.523712,-0.166239,-1.468177,-0.001893
4,-1.643540,-0.707685,-0.071841,-0.032517,1.111611,0.286998,-0.031652,0.986148,-0.120330,0.092991,...,-1.278177,1.0,0.898580,-0.263085,0.201942,-0.008660,-0.591851,-0.166239,-1.468177,-0.791933
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,-0.986659,-1.401088,-0.071841,-1.200460,1.111611,0.952446,-0.904118,-0.282772,-0.349591,-0.429863,...,1.210998,1.0,0.898580,-0.236675,0.338301,-0.248527,0.523712,-0.166239,0.835744,0.271118
1404,0.240845,1.372525,-0.071841,-0.733283,-1.326315,0.370179,1.259599,1.581989,2.355691,2.358690,...,1.210998,-1.0,-1.112867,0.938327,-1.488902,0.391118,-1.168866,-0.166239,0.835744,-0.944143
1405,0.333737,1.372525,-0.071841,-0.032517,-0.745856,-2.208431,-0.904118,-1.783409,-1.495896,-1.344856,...,1.210998,-1.0,-1.112867,-0.274369,1.429168,-0.288505,0.869922,-0.166239,0.835744,1.367994
1406,0.897726,-1.401088,-0.071841,1.836193,-0.745856,0.578131,-0.799422,-0.801374,-0.899817,-0.952716,...,1.210998,-1.0,0.898580,-0.224450,-0.316220,-0.208549,0.100568,-0.166239,0.547754,-0.139606
1407,1.322376,1.372525,-0.071841,-1.667637,0.879428,-2.000478,-0.834321,-0.183465,-0.441295,-0.320935,...,1.210998,-1.0,-1.112867,-0.265386,0.801919,-0.288505,0.869922,-0.166239,0.835744,1.092567

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [38]:
x_train

,Rk,Pos1,Pos2,Age,Tm,G,GS,MP,FG,FGA,...,Season,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score
1014,-0.535469,0.679122,-0.071841,0.901838,-0.281489,0.578131,1.468991,1.118558,1.255237,1.269412,...,1.210998,1.0,0.898580,0.331648,-1.216185,0.151251,-0.784189,-0.166239,0.835744,-0.622811
1117,-1.497567,-0.014282,-0.071841,1.836193,-0.978040,-0.669583,-0.904118,-0.040022,0.429897,0.637630,...,1.210998,1.0,-1.112867,-0.122346,-0.670752,-0.008660,-0.668786,-0.166239,0.259764,-0.533419
125,1.269294,1.372525,-0.071841,2.069781,-1.326315,0.245407,1.154903,1.074421,1.667907,1.901193,...,-1.278177,-1.0,-1.112867,2.011482,-1.625260,1.030763,-1.245801,-0.086895,0.259764,-1.729352
805,1.561241,-0.707685,-0.071841,-0.966871,-1.326315,-0.004135,-0.345740,-0.437249,-0.624704,-0.625933,...,-0.033590,1.0,0.898580,-0.267760,0.911006,-0.288505,1.370002,-0.166239,1.123734,1.599933
435,0.572603,-1.401088,-0.071841,1.369015,-0.629765,0.661312,1.538788,-0.227602,-0.441295,-0.604147,...,-1.278177,1.0,0.898580,3.293646,-1.625260,0.471074,-1.014995,-0.166239,-1.468177,-1.668951
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,1.163132,-1.401088,-0.071841,-1.200460,0.298969,1.160398,1.957572,1.857842,2.997622,2.358690,...,-1.278177,1.0,0.898580,0.582304,-1.488902,0.511052,-1.091931,0.071793,0.547754,-1.637543
323,0.957442,-0.707685,-0.071841,-0.966871,1.459887,0.037455,0.422031,-0.503454,-0.624704,-0.756646,...,-1.278177,-1.0,0.898580,-0.255225,-0.261676,-0.288505,-1.476607,-0.166239,-1.468177,-0.581739
997,1.747026,-0.707685,-0.071841,-0.733283,0.415061,-1.376621,-0.834321,-0.900681,-0.166182,-0.342720,...,1.210998,-1.0,0.898580,-0.259759,1.020093,-0.288505,1.908549,-0.166239,0.547754,1.527452
210,-0.216981,-0.707685,-0.071841,0.668249,-1.558499,0.994036,-0.694726,-0.481386,-0.808113,-0.822003,...,-1.278177,-1.0,0.898580,-0.263832,0.229214,-0.288505,-1.476607,-0.166239,-1.468177,-0.364297
1137,0.459805,-0.707685,-0.071841,-0.499694,0.763336,-0.503221,-0.869220,-1.364113,-1.037374,-1.018073,...,1.210998,-1.0,0.898580,-0.271417,1.865515,-0.288505,1.908549,-0.166239,0.547754,1.899520

In [39]:
x_test

,Rk,Pos1,Pos2,Age,Tm,G,GS,MP,FG,FGA,...,Season,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score
162,-1.530742,-0.014282,-0.071841,1.369015,-0.978040,-0.794354,-0.694726,0.202728,0.384045,0.572273,...,-1.278177,1.0,-1.112867,-0.258529,-0.507122,-0.248527,-0.091771,-0.166239,-1.468177,-1.052864
490,-0.283333,1.372525,-0.071841,-0.266105,1.227703,1.077217,-0.485334,0.566853,0.888419,0.986199,...,-0.033590,1.0,-1.112867,-0.265347,-0.152590,-0.288505,0.523712,-0.166239,0.547754,0.570706
1290,-0.960119,1.372525,-0.071841,-0.032517,0.182877,0.286998,-0.834321,0.059285,-0.257886,-0.320935,...,1.210998,-1.0,-1.112867,-0.270817,-0.561665,-0.288505,0.869922,-0.166239,0.835744,0.488561
969,1.003888,-0.707685,-0.071841,-0.733283,1.692070,-0.170497,0.073044,0.644092,1.071828,1.182269,...,1.210998,-1.0,0.898580,-0.255528,0.720104,-0.208549,0.100568,-0.166239,0.547754,0.319439
296,-1.132633,-0.014282,-0.071841,0.668249,-0.049306,0.619722,1.468991,1.438546,1.576203,1.617981,...,-1.278177,1.0,-1.112867,-0.257017,-1.188914,0.391118,-1.207334,-0.166239,-1.468177,-1.531237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594,-0.396130,1.372525,-0.071841,-0.733283,-0.861948,0.536541,1.364295,1.570955,1.530351,1.400125,...,-0.033590,1.0,-1.112867,-0.243534,-0.534393,-0.208549,-0.437980,-0.166239,0.547754,-0.429529
1398,-0.243522,-1.401088,-0.071841,-0.499694,-1.210223,0.162226,-0.799422,-0.679999,-0.303738,-0.451648,...,1.210998,-1.0,0.898580,-0.218296,-0.398035,-0.248527,0.716051,-0.166239,0.547754,-0.081622
930,0.187764,1.372525,-0.071841,-0.966871,-1.326315,-1.251850,-0.066550,0.787535,1.117681,1.661552,...,-0.033590,-1.0,-1.112867,-0.210239,-1.025283,-0.248527,-0.091771,-0.166239,0.259764,-0.550331
169,0.678765,-1.401088,-0.071841,-1.200460,1.459887,-0.004135,-0.764524,-0.944818,-0.945670,-1.105215,...,-1.278177,-1.0,0.898580,-0.274589,0.311029,-0.288505,-1.476607,-0.166239,-1.468177,-0.328056
395,-0.780969,-0.014282,-0.071841,-0.032517,0.415061,0.453360,0.317335,0.368239,-0.349591,-0.212007,...,-1.278177,1.0,-1.112867,-0.271071,0.474659,-0.208549,-0.476447,-0.166239,-1.468177,-0.678380

In [40]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [41]:
y_pred=model.predict(x_test)

In [42]:
accuracy_score(y_test,y_pred)

0.9822695035460993

# check for overfitting

In [43]:
y_pred_train=model.predict(x_train)

In [44]:
accuracy_score(y_train,y_pred_train)

0.9902309058614565

## if the training_score is more than 80% and difference of more than 10% then it is overfitting

## .overfitting is a problem suffered by powerful and complex models like tree based models

# Transform the data with PCA

In [47]:
from sklearn.decomposition import PCA
pca=PCA(n_components=0.9) # n_components=22 
pca_data=pca.fit_transform(X)

In [48]:
pca_data

array([[-4.22171185,  0.40396211,  2.10111589, ...,  1.72146633,
         1.01528766, -0.64576995],
       [-2.04983915, -1.99827529,  0.54878226, ...,  0.80287028,
         0.52341426, -0.17519516],
       [ 2.84299536,  0.24616161, -0.16959082, ..., -1.18222315,
         0.06813948,  1.0508319 ],
       ...,
       [-7.12892067, -3.72913226,  4.50163821, ...,  0.1027382 ,
        -0.90155088, -0.44778772],
       [-1.78465921,  2.02318092,  0.72097949, ...,  0.0503706 ,
         0.18004463, -0.38352828],
       [-2.56260913, -1.36414077, -0.53083526, ...,  0.16531975,
        -0.09527334, -0.39053885]])

In [49]:
pca_data.shape

(1408, 17)

In [50]:
pca_dataframe=pd.DataFrame(pca_data)

In [51]:
pca_dataframe

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,-4.221712,0.403962,2.101116,-1.923920,0.350704,-0.085770,-0.263837,-1.621786,-0.402664,0.401018,0.249114,1.939383,-0.564768,0.299166,1.721466,1.015288,-0.645770
1,-2.049839,-1.998275,0.548782,-2.844758,0.802633,-0.713360,-0.755533,0.417848,0.623101,-0.253567,-0.757937,-0.412327,0.538463,-0.410189,0.802870,0.523414,-0.175195
2,2.842995,0.246162,-0.169591,-2.474036,-0.892856,0.743317,-0.053201,-1.359370,0.449317,0.046933,0.555316,-0.287679,0.866794,0.153695,-1.182223,0.068139,1.050832
3,-3.555854,0.908923,1.453631,-1.249615,0.259063,0.211891,0.579277,-0.509718,-1.087150,1.039575,-0.622975,0.322877,-1.112644,-0.477609,-0.406657,0.094659,-0.369192
4,1.492529,0.738592,0.483140,-2.014092,-1.037851,-1.743203,0.846236,-1.892563,-0.578415,-0.055352,0.150070,0.232612,0.132833,-0.830623,0.270785,0.698856,-0.130429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,-0.889306,2.373146,-0.756424,0.791881,0.000890,-0.434179,1.253139,-1.544082,0.173146,-0.508277,-0.412395,-0.913997,-0.341178,0.750577,0.487352,1.118407,-0.147608
1404,7.393132,-2.320152,-0.832530,1.500371,-1.180299,1.948774,-0.685001,1.138337,1.252330,-0.480390,-0.997869,1.414311,0.415294,0.906573,-0.217819,-0.322697,-0.158355
1405,-7.128921,-3.729132,4.501638,2.666423,-5.791420,-0.712591,-0.867852,0.609745,0.089535,-0.742610,1.970537,0.222166,0.903914,-0.772870,0.102738,-0.901551,-0.447788
1406,-1.784659,2.023181,0.720979,0.279065,-0.592975,-1.208632,-1.560965,1.973150,-0.015348,0.038845,-0.566864,-1.662800,-0.548231,0.570380,0.050371,0.180045,-0.383528
1407,-2.562609,-1.364141,-0.530835,2.135465,-0.235690,2.150257,0.198545,-0.289834,-0.142841,0.546211,0.105597,-0.362724,0.982730,0.357246,0.165320,-0.095273,-0.390539

In [53]:
x_train,x_test,y_train,y_test=train_test_split(pca_data,y,test_size=0.2)

In [54]:
model1=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [55]:
y_pred=model.predict(x_test)

In [56]:
accuracy_score(y_test,y_pred)

0.975177304964539